version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gdp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gdp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./user.sql:/docker-entrypoint-initdb.d/user.sql
    networks:
      - gdp-network

  mongodb:
    image: mongo:latest
    container_name: gdp-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: gdp
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - gdp-network

  redis:
    image: redis:latest
    container_name: gdp-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gdp-network

networks:
  gdp-network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
  redis_data: