database:
  use: mongo
  maxIdleCon: 10
  maxOpenConn: 30
  connMaxLifeTime: 4h
  connMaxIdleTime: 20m

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: password
  database: gdp

mongo:
  host: 127.0.0.1
  port: 27017
  user: root
  password: password
  database: gdp
  collection: users