database:
  use: mysql
  maxIdleCon: 20


mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: password
  database: gdp


mongo:
  host: 127.0.0.1
  port: 27017
  user: root
  password: password
  database: gdp
  collection: users