database:
  use: mongo
  maxIdleCon: 10
  maxOpenConn: 30
  connMaxLifeTime: 4h
  connMaxIdleTime: 20m
cache:
  use: redis

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: password
  database: gdp

mongo:
  host: 127.0.0.1
  port: 27017
  user: root
  password: password
  database: gdp
  collection: users

json:
  file: ./deployment/data.json

redis:
  ip: 127.0.0.1
  port: 6379
  pool_size: 100
  max_conn: 100
  conn_timeout: 1000
  read_timeout: 1000
  write_timeout: 100



memory:
  default_expiration: 1h
  cleanup_interval: 24h
